In [4]:
import numpy as np
a = np.arange(-5,5)
a

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [5]:
limit = 3

np.clip(a, -limit , limit)

array([-3, -3, -3, -2, -1,  0,  1,  2,  3,  3])

In [14]:

np.random.rand(3,2)


array([[ 0.56804456,  0.92559664],
       [ 0.07103606,  0.0871293 ],
       [ 0.0202184 ,  0.83261985]])